name: AWS OIDC Test

on:
    workflow_dispatch:

permissions:
  id-token: write

jobs:
  run_job_with_aws:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@main # Or a specific version
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: eu-west-1
          mask-aws-account-id: true
      - name: Additional steps
        run: |
          # Your commands that require AWS credentials
          aws sts get-caller-identity 
          aws s3 ls